import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import SideBar from '@/components/sideBar'
import Navbar from '@/components/navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Image Gallery',
  description: 'Generated by Muhammad Anas',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>

        <Navbar />
        <div className='flex flex-col sm:flex-row'>
          <SideBar />
          <div className='w-full px-4 pt-6'>
            {children}
          </div>
        </div>

      </body>
    </html>
  )
}
